version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - DB_NAME=${DB_NAME}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - JINA_API_KEY=${JINA_API_KEY}
  db:
    image: mongo:latest
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
